version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: YourStrongPassword123
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
